### ISSUE TITLE
How would people like their, say, HP be displayed?

### ISSUE THREAD

**Issue by dd86k** [dd86k/fwod#3]
There are three choices here.
`_` indicates a space, and to the right: their format (IFormatProvider)
- `HP: 002` `"{0:000}"`
- `HP: __2` `"{0,3}"`
- `HP: 2__` `"{0,-3}"`

**Comment by gsass1** [comment]
First :+1:

**Comment by dd86k** [comment]
Then first choice it is.

Woop.
