### ISSUE TITLE
Needs more memes

### ISSUE THREAD

**Issue by pt300** [dd86k/fwod#5]
DD pls add morz memz. pls pls!

**Comment by dd86k** [comment]
Hm, it is true that _the game is still quite lacking_ (mostly because I haven't been working on it as of lately).

But, yes, it should include more **memes**. Not the mainstream ones, though.

**Comment by pt300** [comment]
Only important ones
![pls](https://raw.githubusercontent.com/pt300/crot/master/output.webp)

**Comment by dd86k** [comment]
Converting your application to C# _might_ take some time.

**Comment by pt300** [comment]
it's always a good experience

**Comment by dd86k** [comment]
I think I'll do that right now.

**Comment by pt300** [comment]
DD you crazy
